mysite/blog/urls.py
from django.conf.urls import patterns, include, url
from . import views

app_name = 'blog'
urlpatterns = [
        url(r'^$', views.main_page, name='main_page'),
        url(r'^ajax/get', views.ajax_get_test, name='ajax_get_test'),
        url(r'^ajax/post', views.ajax_post_test, name='ajax_post_test'),
        url(r'^upload_file$', views.upload_file, name='upload_file'),
        url(r'^post$', views.post_list, name='post_list'),
        url(r'^post/new$', views.post_new, name='post_new'),
        url(r'^post/get_tag_cloud_list$', views.get_tag_cloud_list, name='get_tag_cloud_list'),
        url(r'^post/get_recent_posts_list$', views.get_recent_posts_list, name='get_recent_posts_list'),
        url(r'^post/recent_comments$', views.recent_comments, name='recent_comments'),
        url(r'^post/(?P<post_id>[0-9]+)/', include(
            [
                url(r'^$', views.post_detail, name='post_detail'),
                url(r'^edit$', views.post_edit, name='post_edit'),
                url(r'^publish$', views.post_publish, name='post_publish'),
                url(r'^remove$', views.post_remove, name='post_remove'),
                url(r'^like$', views.post_like, name='post_like'),
                url(r'^dislike$', views.post_dislike, name='post_dislike'),
                url(r'^new_comment$', views.post_new_comment, name="post_new_comment"),
                ]
            )),
        url(r'^drafts$', views.post_draft_list, name='post_draft_list'),
        url(r'^about$', views.about_me, name="about_me"),
        url(r'^message_board$', views.message_board, name="message_board"),
        url(r'^tag/(?P<tagname>\w+)$', views.get_tag_post_list, name="get_tag_post_list"),
        ]

mysite/blog/models.py
from django import forms
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.
class Tag(models.Model):
    tag_name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.tag_name

class Post(models.Model):
    author = models.ForeignKey(User)
    title = models.CharField(max_length=200)
    text = models.TextField()

    tags = models.ManyToManyField(Tag)
    create_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

    like = models.IntegerField(default=0)
    dislike = models.IntegerField(default=0)
    visited = models.IntegerField(default=0)

    def __str__(self):
        return self.title

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def get_tag_list(self):
        return [x.tag_name for x in self.tags.all()]

    class Meta:
        ordering = ['-create_date']


class Comment(models.Model):
    post = models.ForeignKey(Post)
    username = models.CharField(max_length=50)
    email = models.EmailField(max_length=254)
    comment = models.TextField()
    date_time = models.DateTimeField(default=timezone.now)
    has_read = models.BooleanField(default=False)

    def __str__(self):
        return self.post.title + ' (' + self.username + ')'

    def submit(self):
        self.date_time = timezone.now()
        self.save()

    class Meta:
        ordering = ['-date_time']


class Message(models.Model):
    username = models.CharField(max_length=50)
    email = models.EmailField(max_length=254)
    message = models.TextField()
    date_time = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.username + ' ' + self.email

    def submit(self):
        self.date_time = timezone.now()
        self.save()

    class Meta:
        ordering = ['-date_time']

mysite/blog/forms.py
from django import forms
from .models import Post, Comment, Message

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'tags', 'text', ]
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'tags': forms.SelectMultiple(attrs={'class': 'form-control'}),
            'text': forms.Textarea(attrs={'class': 'form-control'}),
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['username', 'email', 'comment', ]
        widgets = {
            'username': forms.TextInput(attrs={'class': "form-control"}),
            'email': forms.TextInput(attrs={'class': "form-control"}),
            'comment': forms.Textarea(attrs={'class': "form-control"}),
        }


class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ['username', 'email', 'message', ]
        widgets = {
            'username': forms.TextInput(attrs={'class': "form-control"}),
            'email': forms.TextInput(attrs={'class': "form-control"}),
            'message': forms.Textarea(attrs={'class': "form-control"}),
        }

class UploadFileForm(forms.Form):
    filename = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), max_length=50)
    file = forms.FileField()

mysite/blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse, Http404
from django.utils import timezone
from .models import Post, Tag, Comment, Message
from .forms import PostForm, CommentForm, MessageForm, UploadFileForm
import json, os

# Create your views here.

# Main Page
def main_page(request):
    return render(request, 'blog/main_page.html')

# Posts
def post_list(request):
    posts = Post.objects.filter(published_date__isnull=False).order_by('-published_date')
    paginator = Paginator(posts, 5)
    page = request.GET.get('page')
    try:
        contacts = paginator.page(page)
    except PageNotAnInteger:
        contacts = paginator.page(1)
    except EmptyPage:
        contacts = paginator.page(paginator.num_pages)
    return render(request, 'blog/post_list.html', {'contacts': contacts})

def get_tag_post_list(request, tagname):
    tag = Tag.objects.filter(tag_name=tagname)[0]
    posts = tag.post_set.filter(published_date__isnull=False).order_by('-published_date')
    paginator = Paginator(posts, 5)
    page = request.GET.get('page')
    try:
        contacts = paginator.page(page)
    except PageNotAnInteger:
        contacts = paginator.page(1)
    except EmptyPage:
        contacts = paginator.page(paginator.num_pages)
    return render(request, 'blog/post_list.html', {'contacts': contacts})

def post_detail(request, post_id):
    post = get_object_or_404(Post, id=post_id)

    if (post.published_date is None) and (not request.user.is_authenticated()):
        raise Http404("Not Found")

    if not (post.published_date is None) and not request.user.is_authenticated():
        post.visited += 1
        post.save()
    form = CommentForm()

    comment_list = Comment.objects.filter(post = post)
    comment_count = len(comment_list)
    if request.user.is_authenticated():
        for comment in comment_list:
            comment.has_read = True
            comment.save()
    return render(request, 'blog/post_detail.html',
            {'post': post, 'form': form, 'comment_list': comment_list, 'comment_count': comment_count})

def post_new_comment(request, post_id):
    if request.method == 'POST':
        post = get_object_or_404(Post, id=post_id)
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.submit()
            return HttpResponse("success")
        else:
            return HttpResponse("error")

@login_required
def post_new(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            post.tags = form.cleaned_data['tags']
            post.save()
            return redirect('blog:post_detail', post_id=post.id)
    else:
        form = PostForm()
    return render(request, 'blog/post_edit.html', {'form': form})

@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.tags = form.cleaned_data['tags']
            post.save()
            return redirect('blog:post_detail', post_id=post.id)
    else:
        form = PostForm(instance=post)
    return render(request, 'blog/post_edit.html', {'form': form})

@login_required
def post_publish(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    post.publish()
    return redirect('blog:post_detail', post_id=post.id)

def post_draft_list(request):
    posts = Post.objects.filter(published_date__isnull=True).order_by('-create_date')
    return render(request, 'blog/post_draft_list.html', {'posts': posts})

def post_remove(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    post.delete()
    return redirect('blog:post_list')

def post_like(request, post_id):
    if request.method == "POST":
        post = get_object_or_404(Post, id=post_id)
        post.like += 1
        post.save()
        return HttpResponse(post.like)

def post_dislike(request, post_id):
    if request.method == "POST":
        post = get_object_or_404(Post, id=post_id)
        post.dislike += 1
        post.save()
        return HttpResponse(post.dislike)


def recent_comments(request):
    if request.method == "GET":
        if request.user.is_authenticated():
            if request.GET.get('action') == 'comments_count':
                return HttpResponse(len(Comment.objects.filter(has_read=False)))
            elif request.GET.get('action') == 'showlist':
                comment_list = Comment.objects.filter(has_read=False)
                return render(request, 'blog/recent_comments.html', {'comment_list': comment_list})



# Test Menu
def ajax_get_test(request):
    return HttpResponse("The data is from ajax get method")

def ajax_post_test(request):
    response_data = {};
    response_data['text'] = 'Hello ' + request.POST.get('data');
    response_data['extra'] = 'one';
    return JsonResponse(response_data);


# About Me
def about_me(request):
    return render(request, 'blog/about.html')

# Message Board
def message_board(request):
    messages = Message.objects.all().order_by('-date_time');
    if request.method == "POST":
        form = MessageForm(request.POST)
        if form.is_valid():
            msg = form.save(commit=False)
            msg.submit()
            return render(request, 'blog/message_board.html', {'form': MessageForm(), 'messages': messages})
    else:
        form = MessageForm()
    return render(request, 'blog/message_board.html', {'form': form, 'messages': messages})


# Sidebar
def get_tag_cloud_list(resuest):
    response_data = {};
    response_data['tag_list'] = [t.tag_name for t in Tag.objects.all()]
    response_data['count'] = [len(t.post_set.all()) for t in Tag.objects.all()]
    max_font_size = max(response_data['count'])
    response_data['size'] = [8.0 + 1.0 * sz / max_font_size * 10.0 for sz in response_data['count']]
    return JsonResponse(response_data)

def get_recent_posts_list(request):
    response_data = {};
    posts = Post.objects.filter(published_date__isnull=False).order_by('-published_date')[:5]
    response_data['title'] = [post.title for post in posts]
    response_data['id'] = [post.pk for post in posts]
    return JsonResponse(response_data)


# Upload file
@login_required
def upload_file(request):
    file_list = []
    for root, dirs, files in os.walk('media'):
        for f in files:
            file_list.append(os.path.join(root, f))
    if request.method == "POST":
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            rescode = storage_file(request.FILES['file'], request.POST['filename'])
            response = redirect('blog:upload_file')
            if rescode == 0:
                return response
            elif rescode == 1:
                response['Location'] += '?error=repetition'
                return response
    else:
        form = UploadFileForm()
        if request.GET.get('error'):
            return render(request, 'blog/upload_file.html', {'form': form, 'file_list': file_list, 'error':'File exists'})
    return render(request, 'blog/upload_file.html', {'form': form, 'file_list': file_list})

def storage_file(file, filename):
    if os.path.exists(os.path.join('media', filename)):
        return 1
    with open(os.path.join('media', filename), 'wb+') as f:
        for chunk in file.chunks():
            f.write(chunk)
    return 0

mysite/templates/blog/about.html
{% extends 'blog/base.html' %}

{% block blog-main %}
<div class="row">
	<div class="post-main lead">
		<p> About Me 正在建设中 </p>
	</div>
</div>
{% endblock %}

mysite/templates/blog/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
	<head>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>
			{% block title %}Index - gaoyb7's blog{% endblock %}
		</title>
		<link href="//cdn.bootcss.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet">
		<link href="data:text/css;charset=utf-8," data-href="//cdn.bootcss.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" rel="stylesheet" id="bs-theme-stylesheet">
		<link href="//cdn.bootcss.com/highlight.js/8.9.1/styles/github.min.css" rel="stylesheet">
		<link rel="stylesheet" href="{% static 'css/blog.css' %}">
	</head>

	<body>
		<div class="modal fade" id="modal-demo">
			<div class="modal-dialog">
				<div class="modal-content">
					<div class="modal-header">
						<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
						<h4>Modal title</h4>
					</div>
					<div class="modal-body">
						<p>This is a modal demo</p>
					</div>
					<div class="modal-footer">
						<button class="btn btn-primary" type="button" data-dismiss="modal">
							ok
						</button>
					</div>
				</div>
			</div>
		</div>

		<nav class="navbar navbar-default navbar-fixed-top">
			<div class="container">
				<div class="navbar-header">
					<a href="{% url 'blog:main_page' %}" class="navbar-brand">GAOYB7'S BLOG</a>
				</div>

				<div class="collpase navbar-collapse">
					<ul class="nav navbar-nav">
						<li><a href="{% url 'blog:post_list' %}" id="posts-navbar">Posts</a></li>
						{% if user.is_authenticated %}
						{% endif %}
						<li><a href="{% url 'blog:message_board' %}">Message Board</a></li>
						<li><a href="{% url 'blog:about_me' %}">About</a></li>
					</ul>

					<ul class="nav navbar-nav navbar-right">
						{% if user.is_authenticated %}
						<li>
							<a href="{% url 'blog:upload_file' %}" data-toggle="tooltip" data-placement="left" title="Upload files">
								<span class="glyphicon glyphicon-upload"></span>
							</a>
						</li>
						<li>
							<a href="{% url 'blog:recent_comments' %}?action=showlist" data-toggle="tooltip" data-placement="left" title="Comments" id="recent-comments">
								<span class="glyphicon glyphicon-comment"></span>
							</a>
						</li>
						<li>
							<a href="{% url 'blog:post_new' %}" data-toggle="tooltip" data-placement="left" title="New Post">
								<span class="glyphicon glyphicon-plus"></span>
							</a>
						</li>
						<li>
							<a href="{% url 'blog:post_draft_list' %}" data-toggle="tooltip" data-placement="left" title="Draft list">
								<span class="glyphicon glyphicon-edit"></span>
							</a>
						</li>
						<li>
							<a href="{% url 'django.contrib.auth.views.logout' %}" data-toggle="tooltip" data-placement="left" title="Logout">
								<span class="glyphicon glyphicon-log-out"></span>
							</a>
						</li>
						{% else %}
						<li>
							<a href="{% url 'django.contrib.auth.views.login' %}" data-toggle="tooltip" data-placement="left" title="Login">
								<span class="glyphicon glyphicon-lock"></span>
							</a>
						</li>
						{% endif %}
					</ul>
				</div>
			</div>
		</nav>

		<div class="container">
			<div class="row">
				<div class="col-md-9">
					{% block blog-main %}
					{% endblock %}
				</div>

				<div class="col-md-3">
					{% block blog-sidebar %}
					<!-- Recent Posts -->
					<div class="panel panel-default navbar-wrapper">
						<div class="panel-heading">
							<h3 class="panel-title">Recent Posts</h3>
						</div>
						<div class="panel-body">
							<ul class="list-unstyled" id="recent-posts-list">
							</ul>
						</div>
					</div>

					<!-- Tag Cloud -->
					<div class="panel panel-default navbar-wrapper">
						<div class="panel-heading">
							<h3 class="panel-title">Tag Cloud</h3>
						</div>
						<div class="panel-body">
							<div id="tag-cloud-list">
							</div>
						</div>
					</div>
					{% endblock %}
				</div>
			</div>
		</div>

		<script src="//cdn.bootcss.com/jquery/2.1.4/jquery.min.js"></script>
		<script src="//cdn.bootcss.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
		<script src="//cdn.bootcss.com/highlight.js/9.0.0/highlight.min.js"></script>
		<script type="text/javascript" async src="//cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-MML-AM_CHTML"></script>
		<script type="text/x-mathjax-config">
MathJax.Hub.Config({
	tex2jax: {inlineMath: [['$','$'], ['\\(','\\)']]}
});
		</script>
		<script src="{% static 'js/main.js' %}"></script>

		<script>
$(document).ready(function() {
	{% if user.is_authenticated %}
	var p = $('#recent-comments');
	$.get('/post/recent_comments', {action: 'comments_count'}, function(data) {
		if (data != "0") {
			p.append('<span class="badge">' + data + '</span>');
		}
	});
	{% endif %}
});
		</script>

		{% block script %}
		{% endblock %}
	</body>
</html>

mysite/templates/blog/main_page.html
{% extends 'blog/base.html' %}

{% block blog-main %}
<div class="jumbotron text-center">
	<h1>Welcome to Gaoyb7's Blog</h1>
</div>
{% endblock %}

{% block blog-sidebar %}
{% endblock %}

mysite/templates/blog/post_detail.html
{% extends 'blog/base.html' %}
{% load staticfiles %}
{% load custom_markdown %}
{% block title %}
Post - {{ post.title }}
{% endblock %}

{% block blog-main %}
<div class="row">
	<div class="post-main">
		<div class="post-header">
			{% if not post.published_date %}
			<div class="alert alert-warning" role="alert">The article has not yet been released</div>
			{% endif %}
			<h1 class="blog-post-title"><a href="{% url 'blog:post_detail' post_id=post.id %}">{{ post.title }}</a></h1>

			<p class="tag-list">
			Tags:
			{% for tg in post.get_tag_list %}
			<a href="{% url 'blog:get_tag_post_list' tagname=tg %}" style="text-decoration: none;"><span class="label label-info">{{ tg }}</span></a>
			{% endfor %}
			</p>

			{% if post.published_date %}
			<p><span class="glyphicon glyphicon-time"></span> Posted on {{ post.published_date }}<span class="pull-right">Visited: {{ post.visited }}</span></p>
			{% else  %}
			<p><span class="glyphicon glyphicon-time"></span> Created on {{ post.create_date }}</p>
			{% endif %}
		</div>

		<hr>
		<div class="post-content">
			{{ post.text | custom_markdown }}
		</div>
		<br>
		<br>

		<div align="right">
			<a type="button" class="btn btn-success" id="like-post"> <span class="glyphicon glyphicon-thumbs-up"></span> {{ post.like }} </a>
			<a type="button" class="btn btn-danger" id="dislike-post"> <span class="glyphicon glyphicon-thumbs-down"></span> {{ post.dislike }} </a>
			<a href="#new-comment-modal" type="button" class="btn btn-primary" data-toggle="modal"> <span class="glyphicon glyphicon-comment"></span> Comment</a>
		</div>

		{% if user.is_authenticated %}
		<hr>
		<div align="right">
			{% if not post.published_date %}
			<a class="btn btn-default" href="{% url 'blog:post_publish' post_id=post.id %}">Publish</a>
			{% endif %}
			<a class="btn btn-default" href="{% url 'blog:post_edit' post_id=post.id %}">Edit</a>
			<a class="btn btn-default" href="{% url 'blog:post_remove' post_id=post.id %}">Delete</a>
		</div>
		{% endif %}

		<div class="modal fade" id="new-comment-modal">
			<div class="modal-dialog">
				<div class="modal-content">
					<div class="modal-header">
						<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
						<h4 class="modal-title">New comment</h4>
					</div>
					<div class="modal-body">
						<form method="POST" id="new-comment" onsubmit="return false;">
							{% csrf_token %}
							{% for field in form %}
							<div class="form-group">
								{# {{ field.errors }} #}
								{{ field.label_tag }}
								{{ field }}
							</div>
							{% endfor %}
							<button class="btn btn-primary" id="comment-submit">Submit</button>
						</form>
					</div>
				</div>
			</div>
		</div>

		{% if comment_count > 0 %}
		<div class="row comment-list">
			<hr>
			{% for comment in comment_list %}
			<div class="media" id="comment-id-{{ comment.id }}" >
				<a class="pull-left" data-toggle="tooltip" data-placement="left" title="{{ comment.email }}">
					<img class="media-object" src="{% static 'img/3frdQ2L.png' %}" alt="">
				</a>
				<div class="media-body">
					<h4 class="media-heading"> {{ comment.username }}
						<small>{{ comment.date_time }}</small>
					</h4>
					{{ comment.comment }}
				</div>
			</div>
			{% endfor %}
			<hr>
		</div>
		{% endif  %}
	</div>
</div>
{% endblock %}

{% block script %}
<script src="//cdn.bootcss.com/markdown.js/0.5.0/markdown.min.js"></script>
<script>
$(document).ready(function() {
	$('#comment-submit').click(function() {
		$('#new-comment span').remove();
		$('#new-comment .form-group').removeClass('has-error');
		var username = $('#id_username').val();
		var email = $('#id_email').val();
		var comment = $('#id_comment').val();
		var is_valid = true;

		$('.form-group').map(function(id, p) {
			var lab = $(p).find('label');
			var ele = $('#'+lab.attr('for'));

			if (ele.val().trim() === "") {
				$(p).addClass('has-error').append(
						'<span class="help-block">' + $(lab).attr('for').substring(3) + ' field is empty</span>');
				is_valid = false;
			}
		});

		if (is_valid) {
			var post_data = {
				'csrfmiddlewaretoken': '{{ csrf_token }}',
				'username': username,
				'email': email,
				'comment': comment
			};
			$.post("{% url 'blog:post_new_comment' post_id=post.id %}", post_data, function(data, status) {
				if (data === "success") {
					window.location.href="{% url 'blog:post_detail' post_id=post.id %}";
				} else {
					$('#id_email').closest('.form-group').addClass('has-error').append(
							'<span class="help-block">Please enter a valid email address.</span>');
				}
			});
		}
	});

	$('#like-post').click(function() {
		var post_data = {'csrfmiddlewaretoken': '{{ csrf_token }}'};
		$.post("{% url 'blog:post_like' post_id=post.id %}", post_data, function(data, status) {
			if (status === "success") {
				alert('Thank you!');
				$('#like-post').html('<span class="glyphicon glyphicon-thumbs-up"></span> ' + data);
			}
		});
	});

	$('#dislike-post').click(function() {
		var post_data = {'csrfmiddlewaretoken': '{{ csrf_token }}'};
		$.post("{% url 'blog:post_dislike' post_id=post.id %}", post_data, function(data, status) {
			if (status === "success") {
				alert('Please comment below to make it better.');
				$('#dislike-post').html('<span class="glyphicon glyphicon-thumbs-down"></span> ' + data);
			}
		});
	});

	$('.post-content table').addClass('table table-bordered table-striped');
});
</script>
{% endblock %}

mysite/templates/blog/post_draft_list.html
{% extends 'blog/base.html' %}
{% load custom_markdown %}
{% block blog-main %}
{% for post in posts %}
<div class="row">
	<div class="post-main">

		<div class="post-header">
			<h2> <a href="{% url 'blog:post_detail' post_id=post.id %}">{{ post.title }}</a> </h2>
			<p class="tag-list">
			Tags:
			{% for tg in post.get_tag_list %}
			<span class="label label-info">{{ tg }}</span>
			{% endfor %}
			</p>
			<p> <p><span class="glyphicon glyphicon-time"></span> Created on {{ post.create_date }}</p> </p>
		</div>

		<hr>
		<div class="post-content">
			{{ post.text|custom_markdown|truncatewords_html:100 }}
		</div>

		<hr>
		<div align="right">
			<a class="btn btn-default" href="{% url 'blog:post_publish' post_id=post.id %}">Publish</a>
			<a class="btn btn-default" href="{% url 'blog:post_edit' post_id=post.id %}">Edit</a>
			<a class="btn btn-default" href="{% url 'blog:post_remove' post_id=post.id %}">Delete</a>
		</div>
	</div>
</div>
{% endfor %}
{% endblock %}

mysite/templates/blog/post_edit.html
{% extends 'blog/base.html' %}
{% load staticfiles %}
{% block blog-main %}
<!--<script src="//cdn.ckeditor.com/4.5.6/full/ckeditor.js"></script>-->
<link href="//cdn.bootcss.com/bootstrap-markdown/2.9.0/css/bootstrap-markdown.min.css" rel="stylesheet">
{% if form %}
{{ form.media }}
{% endif %}
<form method="POST" tabindex="0">
	{% csrf_token %}
	{% for field in form %}
	<div class="form-group">
		{{ field.errors }}
		{{ field.label_tag }}
		{{ field }}
	</div>
	{% endfor %}
	<button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}

{% block script %}
<script src="//cdn.bootcss.com/bootstrap-markdown/2.9.0/js/bootstrap-markdown.min.js"></script>
<!--<script src="//cdn.bootcss.com/markdown.js/0.5.0/markdown.min.js"></script>-->
<script src="//cdn.bootcss.com/marked/0.3.5/marked.min.js"></script>
<script src="//cdn.bootcss.com/to-markdown/1.3.0/to-markdown.min.js"></script>
<script>
$(document).ready(function() {
	$("#id_text").markdown({autofocus:false,savable:false,height:600})
});
</script>
{% endblock %}

mysite/templates/blog/upload_file.html
{% extends 'blog/base.html' %}

{% block blog-main %}
{% if form %}
{{ form.media }}
{% endif %}
<div class="row">
	<div class="col-md-9">
		{% if error %}
		<div class="alert alert-danger" role="alert">Error: {{ error }}!</div>
		{% endif %}
		<h3>Upload File:</h3>
		<form method="POST" enctype="multipart/form-data" id="upload-file-form">
			{% csrf_token %}
			{% for field in form %}
			<div class="form-group">
				{{ field.errors }}
				{{ field.label_tag }}
				{{ field }}
			</div>
			{% endfor %}
			<button type="submit" class="btn btn-primary">Submit</button>
		</form>
	</div>
</div>

<div class="row">
	<div class="col-md-9">
		<hr>
		<h3>File List:</h3>
		<ul class="list-group">
			{% for file in file_list %}
			<li class=list-group-item><span><a href="{{ file }}">{{ file }}</a></span> <span><a class="pull-right" href="" style="color:red;">delete</a></span></li>
			{% endfor %}
		</ul>
	</div>
</div>
{% endblock %}

{% block script %}
<script>
$(document).ready(function() {
	$('#id_file').change(function() {
		$('#id_filename').val($(this).val())
	});
});
</script>
{% endblock %}